pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = uri('https://repo.spring.io/release') }
    }
}

rootProject.name = 'my-multiservice'

include 'api-gateway', 'config-server', 'eureka-server', 'notification-for-userservice', 'user-service-spring'